**CHAPTER 4**
**TEXT PRE-PROCESSING PADA DATA KOMENTAR TIKTOK HASIL WEB SCRAPING**



Nama: Tabrizzi Aqlia
NIM: 25031554008

Pada Exercise 4 ini, saya menerapkan Text Pre-processing pada data komentar TikTok hasil web scraping dari beberapa video. Setelah revisi, data diperbanyak dengan menambah jumlah komentar per video dan jumlah video yang di-scrape. Tahapan preprocessing: cleaning, case folding, tokenisasi, stopword removal, dan stemming (Sastrawi). Hasil akhirnya disimpan pada kolom prepro, sedangkan kolom text_original dipertahankan sebagai pembanding.

**Install library**

In [1]:
!pip install -q apify-client pandas openpyxl nltk Sastrawi

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.2/160.2 kB 3.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 24.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 6.4 MB/s eta 0:00:00

**Token**

In [3]:
from apify_client import ApifyClient

client = ApifyClient("apify_api_DIivCDNfY4ClmcH5Wczo8Zyi9Ey6Ze19xM2S")

**Scraping**

In [46]:
run_input = {
    "commentsPerPost": 1000,
    "excludePinnedPosts": False,
    "maxRepliesPerComment": 5,
    "postURLs": [
        "https://vt.tiktok.com/ZSqcuwEQm/",
        "https://vt.tiktok.com/ZSbqDmumT/",
        "https://vt.tiktok.com/ZSbqDPGwA/",

    ],
    "resultsPerPage": 100
}

run = client.actor("clockworks/tiktok-comments-scraper").call(run_input=run_input)

[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> Status: RUNNING, Message:
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:21.926Z ACTOR: Pulling container image of build vbgTC88uIvZm0IDk6 from registry.
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:21.929Z ACTOR: Creating container.
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:21.995Z ACTOR: Starting container.
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:21.998Z ACTOR: Running under "LIMITED_PERMISSIONS".
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:22.095Z Running on architecture: x86_64
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:22.099Z Will run command: xvfb-run -a -s "-ac -screen 0 1920x1080x24+32 -nolisten tcp" /bin/bash -o pipefail -c bash -c "    java         --enable-native-access=ALL-UNNAMED         -cp classes-test:classes-main:lib/*         com.zhiliaoapp.musically.MetaSec         > /dev/null &     node dist/src/entrypoint.js "
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:24.401Z INFO  System info {"apifyVersion":"3.7.0","apifyClientVersion":"2.23.0","crawleeVersion":"3.16.0","osType":"Linux","nodeVersion":"v24.21.0"}
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> Status: RUNNING, Message: Starting the crawler.
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:25.002Z INFO  CheerioCrawler: Starting the crawler.
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:26.829Z INFO  [POST] Starting the post scrape.  --- https://vt.tiktok.com/ZSbqDPGwA/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:26.832Z INFO  [POST] Starting the comments scrape.  --- https://vt.tiktok.com/ZSbqDPGwA/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:27.111Z INFO  [POST] Starting the post scrape.  --- https://vt.tiktok.com/ZSbqDmumT/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:27.126Z INFO  [POST] Starting the comments scrape.  --- https://vt.tiktok.com/ZSbqDmumT/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:28.281Z INFO  [POST] Starting the post scrape.  --- https://vt.tiktok.com/ZSqcuwEQm/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:28.283Z INFO  [POST] Starting the comments scrape.  --- https://vt.tiktok.com/ZSqcuwEQm/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:28.304Z INFO  Scraped 31 new comments. --- https://vt.tiktok.com/ZSbqDmumT/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:28.306Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSbqDmumT/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:28.333Z INFO  Scraped 31 new comments. --- https://vt.tiktok.com/ZSbqDmumT/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:28.335Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSbqDmumT/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:28.401Z INFO  Scraped 27 new comments. --- https://vt.tiktok.com/ZSbqDPGwA/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:28.403Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSbqDPGwA/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:28.474Z INFO  Scraped 27 new comments. --- https://vt.tiktok.com/ZSbqDPGwA/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:28.476Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSbqDPGwA/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:28.736Z INFO  Scraped 27 new comments. --- https://vt.tiktok.com/ZSbqDPGwA/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:28.738Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSbqDPGwA/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:29.396Z INFO  Scraped 31 new comments. --- https://vt.tiktok.com/ZSbqDmumT/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:29.398Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSbqDmumT/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:29.588Z INFO  Scraped 30 new comments. --- https://vt.tiktok.com/ZSqcuwEQm/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:29.589Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSqcuwEQm/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:29.749Z INFO  Scraped 30 new comments. --- https://vt.tiktok.com/ZSqcuwEQm/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:29.751Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSqcuwEQm/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:29.977Z INFO  Scraped 28 new comments. --- https://vt.tiktok.com/ZSbqDmumT/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:29.979Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSbqDmumT/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:30.005Z WARN  Failed to parse response status {"error":"✖ Invalid input: expected object, received undefined"}
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:30.014Z INFO  Scraped 31 new comments. --- https://vt.tiktok.com/ZSbqDmumT/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:30.016Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSbqDmumT/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:30.445Z INFO  Scraped 27 new comments. --- https://vt.tiktok.com/ZSbqDPGwA/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:30.447Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSbqDPGwA/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:30.615Z WARN  Failed to parse response status {"error":"✖ Invalid input: expected object, received undefined"}
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:30.622Z INFO  Scraped 30 new comments. --- https://vt.tiktok.com/ZSqcuwEQm/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:30.624Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSqcuwEQm/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:30.799Z WARN  Failed to parse response status {"error":"✖ Invalid input: expected object, received undefined"}
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:30.805Z INFO  Scraped 27 new comments. --- https://vt.tiktok.com/ZSbqDPGwA/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:30.823Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSbqDPGwA/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:31.234Z INFO  Scraped 31 new comments. --- https://vt.tiktok.com/ZSqcuwEQm/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:31.236Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSqcuwEQm/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:31.538Z INFO  Scraped 30 new comments. --- https://vt.tiktok.com/ZSqcuwEQm/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:31.539Z WARN  The post has no more top-level comments to scrape. --- https://vt.tiktok.com/ZSqcuwEQm/
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:31.592Z INFO  CheerioCrawler: All requests from the queue have been processed, the crawler will shut down.
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:31.813Z INFO  CheerioCrawler: Final request statistics: {"requestsFinished":18,"requestsFailed":0,"retryHistogram":[18],"requestAvgFailedDurationMillis":null,"requestAvgFinishedDurationMillis":2128,"requestsFinishedPerMinute":154,"requestsFailedPerMinute":0,"requestTotalDurationMillis":38307,"requestsTotal":18,"crawlerRuntimeMillis":6991}
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:31.815Z INFO  CheerioCrawler: Finished! Total 18 requests: 18 succeeded, 0 failed. {"terminal":true}
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:31.817Z INFO  [Status message]: Scraped 3/3 posts for top-level comments. Total comments scraped: 0.
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> 2026-10-07T10:28:31.907Z INFO  [Status message]: Scraped 3/3 posts for top-level comments. Total comments scraped: 0.
[apify.tiktok-comments-scraper runId:5XHMZ0XsvQLNHi25i] -> Status: SUCCEEDED, Message: Scraped 3/3 posts for top-level comments. Total comments scraped: 0.

**Ambil hasil scraping**

In [5]:
items = list(client.dataset(run.default_dataset_id).iterate_items())
print("Jumlah data hasil scraping:", len(items))

Jumlah data hasil scraping: 1346

**Jadikan DataFrame**

In [6]:
import pandas as pd

df = pd.DataFrame(items)
print("Jumlah data:", len(df))
print("Jumlah kolom:", len(df.columns))
print("Nama kolom:", df.columns.tolist())
df[['uniqueId', 'text', 'createTimeISO', 'diggCount']].head(10)

Jumlah data: 1346
Jumlah kolom: 17
Nama kolom: ['videoWebUrl', 'submittedVideoUrl', 'input', 'cid', 'createTime', 'createTimeISO', 'text', 'diggCount', 'likedByAuthor', 'pinnedByAuthor', 'repliesToId', 'replyCommentTotal', 'uid', 'uniqueId', 'avatarThumbnail', 'mentions', 'detailedMentions']

,uniqueId,text,createTimeISO,diggCount
0,sallsabilaadriani_,AGUSTUS JAHAT.,2026-08-26T23:49:59.000Z,4246
1,user0856704433,monyet nya gimana ya,2026-08-25T13:14:34.000Z,9430
2,fatirrrrrrr35,kondisi hewannya gimana termasuk ini?,2026-08-25T13:17:26.000Z,1334
3,orngjahatktny,"yaallah kasian banget hewan hewan disana, leka...",2026-08-27T06:39:56.000Z,633
4,apacba02,semoga cepat hujan ya kalimantan,2026-08-27T09:04:54.000Z,71
5,biru_langit_5,"semoga kalimantan cepat pulih""aminnnn🤲",2026-08-25T10:50:36.000Z,111
6,rossell_2,Aku kasian sama hewan2 nya,2026-08-31T12:23:38.000Z,61
7,pengguna_akun508,hewan hewan nya gimna yaa🥺,2026-08-27T06:33:30.000Z,96
8,juviaaww,semangat ya saudara saudara ku yang disana.,2026-08-27T03:28:07.000Z,112
9,alvaulianmauza,ya Allah semoga cepat sembuh Kalimantan,2026-08-27T08:10:37.000Z,5

**Simpan teks asli**

In [8]:
print("Total baris:", len(df))
print("Komentar per video:")
print(df['videoWebUrl'].value_counts())

Total baris: 1346
Komentar per video:
videoWebUrl
https://www.tiktok.com/@bbcnewsindonesia/video/7693162679644474644    500
https://www.tiktok.com/@wwabula2/video/7677914744132619528            426
https://www.tiktok.com/@officialinews/video/7680919403432578324       420
Name: count, dtype: int64

In [29]:
import pandas as pd

df = pd.DataFrame(items)
print("Jumlah data:", len(df))
print("Jumlah kolom:", len(df.columns))
print("Nama kolom:", df.columns.tolist())
df[['uniqueId', 'text', 'createTimeISO', 'diggCount']].head(1000)

Jumlah data: 1346
Jumlah kolom: 17
Nama kolom: ['videoWebUrl', 'submittedVideoUrl', 'input', 'cid', 'createTime', 'createTimeISO', 'text', 'diggCount', 'likedByAuthor', 'pinnedByAuthor', 'repliesToId', 'replyCommentTotal', 'uid', 'uniqueId', 'avatarThumbnail', 'mentions', 'detailedMentions']

,uniqueId,text,createTimeISO,diggCount
0,sallsabilaadriani_,AGUSTUS JAHAT.,2026-08-26T23:49:59.000Z,4246
1,user0856704433,monyet nya gimana ya,2026-08-25T13:14:34.000Z,9430
2,fatirrrrrrr35,kondisi hewannya gimana termasuk ini?,2026-08-25T13:17:26.000Z,1334
3,orngjahatktny,"yaallah kasian banget hewan hewan disana, leka...",2026-08-27T06:39:56.000Z,633
4,apacba02,semoga cepat hujan ya kalimantan,2026-08-27T09:04:54.000Z,71
...,...,...,...,...
995,antoniusantonius2,panglima asap udah ada p5 air lg kemana ya,2026-09-09T14:04:13.000Z,0
996,ciminimini_,lah belom selesai kah ku kira udah,2026-09-09T12:53:15.000Z,0
997,sary.chally,wkwkw,2026-08-28T01:29:55.000Z,0
998,kikidahlia251,Kon ada yg tega ya yg bakar semoga cepat dpt azab,2026-08-25T17:27:13.000Z,3
999,adella5566,lagu ini jadi ingetin temen aku yang udh almar...,2026-08-26T06:33:23.000Z,3

**Simpan teks asli**

In [30]:
data = df.copy()
data['text_original'] = data['text']
data[['text_original']].head(1000)

                                         text_original
0                                       AGUSTUS JAHAT.
1                                 monyet nya gimana ya
2                kondisi hewannya gimana termasuk ini?
3    yaallah kasian banget hewan hewan disana, leka...
4                     semoga cepat hujan ya kalimantan
..                                                 ...
995         panglima asap udah ada p5 air lg kemana ya
996                 lah belom selesai kah ku kira udah
997                                              wkwkw
998  Kon ada yg tega ya yg bakar semoga cepat dpt azab
999  lagu ini jadi ingetin temen aku yang udh almar...

[1000 rows x 1 columns]

**Lowercase**

In [31]:
data['text_clean'] = data['text'].astype(str).str.lower()
data[['text_original', 'text_clean']].head(1000)

,text_original,text_clean
0,AGUSTUS JAHAT.,agustus jahat.
1,monyet nya gimana ya,monyet nya gimana ya
2,kondisi hewannya gimana termasuk ini?,kondisi hewannya gimana termasuk ini?
3,"yaallah kasian banget hewan hewan disana, leka...","yaallah kasian banget hewan hewan disana, leka..."
4,semoga cepat hujan ya kalimantan,semoga cepat hujan ya kalimantan
...,...,...
995,panglima asap udah ada p5 air lg kemana ya,panglima asap udah ada p5 air lg kemana ya
996,lah belom selesai kah ku kira udah,lah belom selesai kah ku kira udah
997,wkwkw,wkwkw
998,Kon ada yg tega ya yg bakar semoga cepat dpt azab,kon ada yg tega ya yg bakar semoga cepat dpt azab
999,lagu ini jadi ingetin temen aku yang udh almar...,lagu ini jadi ingetin temen aku yang udh almar...

**Hapus URL**

In [32]:
import re

data['text_clean'] = data['text_clean'].apply(
    lambda x: re.sub(r'http\S+|www\S+|https\S+', '', x)
)
data[['text_original', 'text_clean']].head(1000)

,text_original,text_clean
0,AGUSTUS JAHAT.,agustus jahat.
1,monyet nya gimana ya,monyet nya gimana ya
2,kondisi hewannya gimana termasuk ini?,kondisi hewannya gimana termasuk ini?
3,"yaallah kasian banget hewan hewan disana, leka...","yaallah kasian banget hewan hewan disana, leka..."
4,semoga cepat hujan ya kalimantan,semoga cepat hujan ya kalimantan
...,...,...
995,panglima asap udah ada p5 air lg kemana ya,panglima asap udah ada p5 air lg kemana ya
996,lah belom selesai kah ku kira udah,lah belom selesai kah ku kira udah
997,wkwkw,wkwkw
998,Kon ada yg tega ya yg bakar semoga cepat dpt azab,kon ada yg tega ya yg bakar semoga cepat dpt azab
999,lagu ini jadi ingetin temen aku yang udh almar...,lagu ini jadi ingetin temen aku yang udh almar...

**Hapus mention & hashtag**

In [33]:
data['text_clean'] = data['text_clean'].apply(
    lambda x: re.sub(r'@\w+|#\w+', '', x)
)
data[['text_original', 'text_clean']].head(1000)

,text_original,text_clean
0,AGUSTUS JAHAT.,agustus jahat.
1,monyet nya gimana ya,monyet nya gimana ya
2,kondisi hewannya gimana termasuk ini?,kondisi hewannya gimana termasuk ini?
3,"yaallah kasian banget hewan hewan disana, leka...","yaallah kasian banget hewan hewan disana, leka..."
4,semoga cepat hujan ya kalimantan,semoga cepat hujan ya kalimantan
...,...,...
995,panglima asap udah ada p5 air lg kemana ya,panglima asap udah ada p5 air lg kemana ya
996,lah belom selesai kah ku kira udah,lah belom selesai kah ku kira udah
997,wkwkw,wkwkw
998,Kon ada yg tega ya yg bakar semoga cepat dpt azab,kon ada yg tega ya yg bakar semoga cepat dpt azab
999,lagu ini jadi ingetin temen aku yang udh almar...,lagu ini jadi ingetin temen aku yang udh almar...

**Hapus tanda baca**

In [34]:
data['text_clean'] = data['text_clean'].apply(
    lambda x: re.sub(r'[^\w\s]', '', x)
)
data[['text_original', 'text_clean']].head(1000)

,text_original,text_clean
0,AGUSTUS JAHAT.,agustus jahat
1,monyet nya gimana ya,monyet nya gimana ya
2,kondisi hewannya gimana termasuk ini?,kondisi hewannya gimana termasuk ini
3,"yaallah kasian banget hewan hewan disana, leka...",yaallah kasian banget hewan hewan disana lekas...
4,semoga cepat hujan ya kalimantan,semoga cepat hujan ya kalimantan
...,...,...
995,panglima asap udah ada p5 air lg kemana ya,panglima asap udah ada p5 air lg kemana ya
996,lah belom selesai kah ku kira udah,lah belom selesai kah ku kira udah
997,wkwkw,wkwkw
998,Kon ada yg tega ya yg bakar semoga cepat dpt azab,kon ada yg tega ya yg bakar semoga cepat dpt azab
999,lagu ini jadi ingetin temen aku yang udh almar...,lagu ini jadi ingetin temen aku yang udh almar...

**Hapus angka**

In [35]:
data['text_clean'] = data['text_clean'].apply(
    lambda x: re.sub(r'\d+', '', x)
)
data[['text_original', 'text_clean']].head(1000)

,text_original,text_clean
0,AGUSTUS JAHAT.,agustus jahat
1,monyet nya gimana ya,monyet nya gimana ya
2,kondisi hewannya gimana termasuk ini?,kondisi hewannya gimana termasuk ini
3,"yaallah kasian banget hewan hewan disana, leka...",yaallah kasian banget hewan hewan disana lekas...
4,semoga cepat hujan ya kalimantan,semoga cepat hujan ya kalimantan
...,...,...
995,panglima asap udah ada p5 air lg kemana ya,panglima asap udah ada p air lg kemana ya
996,lah belom selesai kah ku kira udah,lah belom selesai kah ku kira udah
997,wkwkw,wkwkw
998,Kon ada yg tega ya yg bakar semoga cepat dpt azab,kon ada yg tega ya yg bakar semoga cepat dpt azab
999,lagu ini jadi ingetin temen aku yang udh almar...,lagu ini jadi ingetin temen aku yang udh almar...

**Rapikan spasi**

In [36]:
data['text_clean'] = data['text_clean'].apply(
    lambda x: re.sub(r'\s+', ' ', x).strip()
)
data[['text_original', 'text_clean']].head(1000)

,text_original,text_clean
0,AGUSTUS JAHAT.,agustus jahat
1,monyet nya gimana ya,monyet nya gimana ya
2,kondisi hewannya gimana termasuk ini?,kondisi hewannya gimana termasuk ini
3,"yaallah kasian banget hewan hewan disana, leka...",yaallah kasian banget hewan hewan disana lekas...
4,semoga cepat hujan ya kalimantan,semoga cepat hujan ya kalimantan
...,...,...
995,panglima asap udah ada p5 air lg kemana ya,panglima asap udah ada p air lg kemana ya
996,lah belom selesai kah ku kira udah,lah belom selesai kah ku kira udah
997,wkwkw,wkwkw
998,Kon ada yg tega ya yg bakar semoga cepat dpt azab,kon ada yg tega ya yg bakar semoga cepat dpt azab
999,lagu ini jadi ingetin temen aku yang udh almar...,lagu ini jadi ingetin temen aku yang udh almar...

**Hapus komentar kosong dan duplikat**

In [37]:
print("Sebelum:", len(data))
data = data[data['text_clean'].str.strip() != ''].copy()
data = data.drop_duplicates(subset='text_clean').reset_index(drop=True)
print("Jumlah komentar setelah cleaning:", len(data))

Sebelum: 1346
Jumlah komentar setelah cleaning: 1273

**Tokenisasi**

In [38]:
import nltk
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')

data['tokens'] = data['text_clean'].apply(word_tokenize)
data[['text_clean', 'tokens']].head(1000)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

,text_clean,tokens
0,agustus jahat,"[agustus, jahat]"
1,monyet nya gimana ya,"[monyet, nya, gimana, ya]"
2,kondisi hewannya gimana termasuk ini,"[kondisi, hewannya, gimana, termasuk, ini]"
3,yaallah kasian banget hewan hewan disana lekas...,"[yaallah, kasian, banget, hewan, hewan, disana..."
4,semoga cepat hujan ya kalimantan,"[semoga, cepat, hujan, ya, kalimantan]"
...,...,...
995,astaghfirullah seharusnya sholat sunah istisqa...,"[astaghfirullah, seharusnya, sholat, sunah, is..."
996,mari berdoa untuk saudara di kalimantan semoga...,"[mari, berdoa, untuk, saudara, di, kalimantan,..."
997,kerana manusia bumi ini hancur tak guna nak sa...,"[kerana, manusia, bumi, ini, hancur, tak, guna..."
998,ulah manusia tdk brtanggung jwb mrusak alam,"[ulah, manusia, tdk, brtanggung, jwb, mrusak, ..."
999,ini bukti kurupsi itu membunuh rakyat,"[ini, bukti, kurupsi, itu, membunuh, rakyat]"

**Stopword Indonesia**

In [19]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

factory = StopWordRemoverFactory()
stopwords = set(factory.get_stop_words())
print("Jumlah stopword:", len(stopwords))

Jumlah stopword: 123

**Hapus stopword**

In [39]:
data['tokens_no_stopword'] = data['tokens'].apply(
    lambda tokens: [w for w in tokens if w not in stopwords]
)
data[['tokens', 'tokens_no_stopword']].head(1000)

,tokens,tokens_no_stopword
0,"[agustus, jahat]","[agustus, jahat]"
1,"[monyet, nya, gimana, ya]","[monyet, nya, gimana]"
2,"[kondisi, hewannya, gimana, termasuk, ini]","[kondisi, hewannya, gimana, termasuk]"
3,"[yaallah, kasian, banget, hewan, hewan, disana...","[yaallah, kasian, banget, hewan, hewan, disana..."
4,"[semoga, cepat, hujan, ya, kalimantan]","[semoga, cepat, hujan, kalimantan]"
...,...,...
995,"[astaghfirullah, seharusnya, sholat, sunah, is...","[astaghfirullah, sholat, sunah, istisqa, minta..."
996,"[mari, berdoa, untuk, saudara, di, kalimantan,...","[berdoa, saudara, kalimantan, semoga, baik, ba..."
997,"[kerana, manusia, bumi, ini, hancur, tak, guna...","[kerana, manusia, bumi, hancur, tak, nak, sala..."
998,"[ulah, manusia, tdk, brtanggung, jwb, mrusak, ...","[ulah, manusia, tdk, brtanggung, jwb, mrusak, ..."
999,"[ini, bukti, kurupsi, itu, membunuh, rakyat]","[bukti, kurupsi, membunuh, rakyat]"

**Gabung jadi teks**

In [40]:
data['text_no_stopword'] = data['tokens_no_stopword'].apply(lambda t: ' '.join(t))
data[['text_clean', 'text_no_stopword']].head(1000)

,text_clean,text_no_stopword
0,agustus jahat,agustus jahat
1,monyet nya gimana ya,monyet nya gimana
2,kondisi hewannya gimana termasuk ini,kondisi hewannya gimana termasuk
3,yaallah kasian banget hewan hewan disana lekas...,yaallah kasian banget hewan hewan disana lekas...
4,semoga cepat hujan ya kalimantan,semoga cepat hujan kalimantan
...,...,...
995,astaghfirullah seharusnya sholat sunah istisqa...,astaghfirullah sholat sunah istisqa minta huja...
996,mari berdoa untuk saudara di kalimantan semoga...,berdoa saudara kalimantan semoga baik baik kal...
997,kerana manusia bumi ini hancur tak guna nak sa...,kerana manusia bumi hancur tak nak salah menya...
998,ulah manusia tdk brtanggung jwb mrusak alam,ulah manusia tdk brtanggung jwb mrusak alam
999,ini bukti kurupsi itu membunuh rakyat,bukti kurupsi membunuh rakyat

**Siapkan stemmer**

In [22]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

stemmer = StemmerFactory().create_stemmer()

**Stemming (versi cepat dengan cache)**

In [42]:
cache = {}

def stem_cepat(teks):
    hasil = []
    for kata in teks.split():
        if kata not in cache:
            cache[kata] = stemmer.stem(kata)
        hasil.append(cache[kata])
    return ' '.join(hasil)

data['text_stemmed'] = data['text_no_stopword'].apply(stem_cepat)
data[['text_no_stopword', 'text_stemmed']].head(1000)

,text_no_stopword,text_stemmed
0,agustus jahat,agustus jahat
1,monyet nya gimana,monyet nya gimana
2,kondisi hewannya gimana termasuk,kondisi hewan gimana masuk
3,yaallah kasian banget hewan hewan disana lekas...,yaallah kasi banget hewan hewan sana lekas pul...
4,semoga cepat hujan kalimantan,moga cepat hujan kalimantan
...,...,...
995,astaghfirullah sholat sunah istisqa minta huja...,astaghfirullah sholat sunah istisqa minta huja...
996,berdoa saudara kalimantan semoga baik baik kal...,doa saudara kalimantan moga baik baik kalian s...
997,kerana manusia bumi hancur tak nak salah menya...,rana manusia bumi hancur tak nak salah salah k...
998,ulah manusia tdk brtanggung jwb mrusak alam,ulah manusia tdk brtanggung jwb mrusak alam
999,bukti kurupsi membunuh rakyat,bukti kurupsi bunuh rakyat

**Kolom prepro**

In [43]:
data['prepro'] = data['text_stemmed']
data[['text_original', 'prepro']].head(1000)

,text_original,prepro
0,AGUSTUS JAHAT.,agustus jahat
1,monyet nya gimana ya,monyet nya gimana
2,kondisi hewannya gimana termasuk ini?,kondisi hewan gimana masuk
3,"yaallah kasian banget hewan hewan disana, leka...",yaallah kasi banget hewan hewan sana lekas pul...
4,semoga cepat hujan ya kalimantan,moga cepat hujan kalimantan
...,...,...
995,Astaghfirullah...\nSeharusnya Sholat Sunah Ist...,astaghfirullah sholat sunah istisqa minta huja...
996,mari berdoa untuk saudara2 di Kalimantan semog...,doa saudara kalimantan moga baik baik kalian s...
997,kerana manusia bumi Ini Hancur..\ntak guna Nak...,rana manusia bumi hancur tak nak salah salah k...
998,Ulah manusia tdk brtanggung jwb mrusak alam .,ulah manusia tdk brtanggung jwb mrusak alam
999,ini bukti kurupsi itu membunuh rakyat,bukti kurupsi bunuh rakyat

**Tabel final + simpan CSV**

In [44]:
hasil_tiktok = data[
    ['uniqueId', 'text_original', 'prepro', 'createTimeISO', 'diggCount']
].copy()

hasil_tiktok = hasil_tiktok[hasil_tiktok['prepro'].str.strip() != ''].reset_index(drop=True)

print("Jumlah data final:", len(hasil_tiktok))
hasil_tiktok.to_csv('hasil_tiktok.csv', index=False)
hasil_tiktok.head(1000)

Jumlah data final: 1265

,uniqueId,text_original,prepro,createTimeISO,diggCount
0,sallsabilaadriani_,AGUSTUS JAHAT.,agustus jahat,2026-08-26T23:49:59.000Z,4246
1,user0856704433,monyet nya gimana ya,monyet nya gimana,2026-08-25T13:14:34.000Z,9430
2,fatirrrrrrr35,kondisi hewannya gimana termasuk ini?,kondisi hewan gimana masuk,2026-08-25T13:17:26.000Z,1334
3,orngjahatktny,"yaallah kasian banget hewan hewan disana, leka...",yaallah kasi banget hewan hewan sana lekas pul...,2026-08-27T06:39:56.000Z,633
4,apacba02,semoga cepat hujan ya kalimantan,moga cepat hujan kalimantan,2026-08-27T09:04:54.000Z,71
...,...,...,...,...,...
995,arikiting82,gawat,gawat,2026-09-15T10:28:02.000Z,0
996,_hqfr,maaf kak..pn nanya ini itu awal mula kebakar n...,maaf kakpn nanya awal mula bakar nya apa,2026-10-05T14:24:47.000Z,1
997,_penjualbunga,"katanya ada yg sengaja ngebakar, gatau jga yg ...",kata yg sengaja ngebakar gatau jga yg jelas,2026-10-05T15:04:47.000Z,1
998,fiongvisualdiaries,lahan kak,lahan kak,2026-10-05T15:04:35.000Z,1
999,aaalindaya,belum sudah 3 bulan belum padam,bulan padam,2026-10-05T15:36:13.000Z,0

**Download CSV**

In [45]:
from google.colab import files
files.download('hasil_tiktok.csv')